# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_win.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector

class Ui_add_win(object):
    def setupUi(self, add_win):
        add_win.setObjectName("add_win")
        add_win.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        add_win.setFont(font)
        ####################YOu dont it it #####################
        #################
        ######################\
        ##################
        self.centralwidget = QtWidgets.QWidget(add_win)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 10, 171, 71))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 90, 171, 71))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 160, 171, 71))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 230, 171, 71))
        self.label_4.setObjectName("label_4")

        ###########inputSSSSSS ###########
        ################ ############
        ###################
        ##########
        self.first_inp = QtWidgets.QLineEdit(self.centralwidget)
        self.first_inp.setGeometry(QtCore.QRect(190, 30, 431, 41))
        self.first_inp.setObjectName("first_inp")
        self.last_inp = QtWidgets.QLineEdit(self.centralwidget)
        self.last_inp.setGeometry(QtCore.QRect(190, 110, 431, 41))
        self.last_inp.setObjectName("last_inp")
        self.phone_inp = QtWidgets.QLineEdit(self.centralwidget)
        self.phone_inp.setGeometry(QtCore.QRect(190, 180, 431, 41))
        self.phone_inp.setObjectName("phone_inp")
        self.price_inp = QtWidgets.QLineEdit(self.centralwidget)
        self.price_inp.setGeometry(QtCore.QRect(190, 250, 431, 41))
        self.price_inp.setObjectName("price_inp")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 360, 171, 71))
        self.label_5.setObjectName("label_5")
        self.depend_combo = QtWidgets.QComboBox(self.centralwidget)
        self.depend_combo.setGeometry(QtCore.QRect(190, 380, 431, 41))
        self.depend_combo.setObjectName("depend_combo")
        self.depend_combo.addItem("")
        self.depend_combo.addItem("")
        self.depend_combo.addItem("")
        self.save_btn = QtWidgets.QPushButton(self.centralwidget,clicked=self.save_func)
        self.save_btn.setGeometry(QtCore.QRect(540, 470, 241, 51))
        self.save_btn.setObjectName("save_btn")
        self.date_inp = QtWidgets.QDateEdit(self.centralwidget)
        self.date_inp.setGeometry(QtCore.QRect(190, 300, 181, 61))
        self.date_inp.setObjectName("date_inp")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(30, 300, 171, 71))
        temp_var = self.date_inp.date()
        self.my_date = temp_var.toPyDate()

        self.label_6.setObjectName("label_6")
        add_win.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(add_win)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 38))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        add_win.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(add_win)
        self.statusbar.setObjectName("statusbar")
        add_win.setStatusBar(self.statusbar)
        self.actionLast_Action = QtWidgets.QAction(add_win)
        self.actionLast_Action.setObjectName("actionLast_Action")
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(add_win)
        QtCore.QMetaObject.connectSlotsByName(add_win)
    def save_func(self):
        print(self.first_inp.text())
        print( self.last_inp.text())
        print(self.phone_inp.text())
        print( self.price_inp.text())
        print(self.my_date)
        print(self.depend_combo.currentText())

        #connect mysql
        mydb=mysql.connector.connect(
            host="localhost",
            user="root",
            passwd="2125253032",
            port="3306",
            database="patiens"
        )
        #create a cursor
        c=mydb.cursor()
        d=f"""INSERT INTO add_win(first_name,last_name,phone,price,date_patient,depend) VALUES
        (%s,%s,%s,%s,%s,%s)"""
        get_me=(
            self.first_inp.text(),
           self.last_inp.text(),
           self.phone_inp.text(),
            self.price_inp.text(),
            self.my_date,
           self.depend_combo.currentText())
        c.execute(d,get_me)
        #commit
        mydb.commit()
        #close
        mydb.close()

    def retranslateUi(self, add_win):
        _translate = QtCore.QCoreApplication.translate
        add_win.setWindowTitle(_translate("add_win", "Add Customer"))
        self.label.setText(_translate("add_win", "First Name"))
        self.label_2.setText(_translate("add_win", "Last Name"))
        self.label_3.setText(_translate("add_win", "Phone No"))
        self.label_4.setText(_translate("add_win", "Price"))
        self.first_inp.setText(_translate("add_win", "first input"))
        self.last_inp.setText(_translate("add_win", "last input"))
        self.phone_inp.setText(_translate("add_win", "phone input"))
        self.price_inp.setText(_translate("add_win", "Price input"))
        self.label_5.setText(_translate("add_win", "Depend"))
        self.depend_combo.setItemText(0, _translate("add_win", "None"))
        self.depend_combo.setItemText(1, _translate("add_win", "REcep turgut"))
        self.depend_combo.setItemText(2, _translate("add_win", "ridvan turgut"))
        self.save_btn.setText(_translate("add_win", "Save Data"))
        self.label_6.setText(_translate("add_win", "Date"))
        self.menuMenu.setTitle(_translate("add_win", "Menu"))
        self.actionLast_Action.setText(_translate("add_win", "History"))


