# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main_win.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from add_win import Ui_add_win
from show_win import Ui_show_win


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(36)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.show_btn = QtWidgets.QPushButton(self.centralwidget, clicked=lambda : self.press_it(1))
        self.show_btn.setGeometry(QtCore.QRect(110, 100, 211, 251))
        self.show_btn.setObjectName("show_btn")
        self.add_btn = QtWidgets.QPushButton(self.centralwidget, clicked=lambda : self.press_it(2))
        self.add_btn.setGeometry(QtCore.QRect(430, 100, 211, 251))
        self.add_btn.setObjectName("add_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 61))
        self.menubar.setObjectName("menubar")
        self.menuhistory = QtWidgets.QMenu(self.menubar)
        self.menuhistory.setObjectName("menuhistory")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionHistory = QtWidgets.QAction(MainWindow)
        self.actionHistory.setObjectName("actionHistory")
        self.menuhistory.addAction(self.actionHistory)
        self.menubar.addAction(self.menuhistory.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    def press_it(self,x):
        if x==1:
            self.show_win = QtWidgets.QMainWindow()
            self.ui = Ui_show_win()
            self.ui.setupUi(self.show_win)
            self.show_win.show()

        elif x==2:
            self.add_win = QtWidgets.QMainWindow()
            self.ui = Ui_add_win()
            self.ui.setupUi(self.add_win)
            self.add_win.show()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Welcome  Noza Shatz"))
        self.show_btn.setText(_translate("MainWindow", "SHOW"))
        self.add_btn.setText(_translate("MainWindow", "ADD"))
        self.menuhistory.setTitle(_translate("MainWindow", "Menu"))
        self.actionHistory.setText(_translate("MainWindow", "History"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
