# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'show_win.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import mysql.connector

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_show_win(object):
    def setupUi(self, show_win):
        show_win.setObjectName("show_win")
        show_win.resize(1080, 601)
        font = QtGui.QFont()
        font.setPointSize(16)
        show_win.setFont(font)
        self.centralwidget = QtWidgets.QWidget(show_win)
        self.centralwidget.setObjectName("centralwidget")
        self.treeWidget = QtWidgets.QTreeWidget(self.centralwidget)
        self.treeWidget.setGeometry(QtCore.QRect(20, 110, 1031, 201))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.treeWidget.setFont(font)
        self.treeWidget.setObjectName("treeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(30, 50, 761, 51))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(810, 50, 241, 51))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(780, 350, 241, 51))
        self.pushButton_2.setObjectName("pushButton_2")
        show_win.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(show_win)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1080, 36))
        self.menubar.setObjectName("menubar")
        show_win.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(show_win)
        self.statusbar.setObjectName("statusbar")
        show_win.setStatusBar(self.statusbar)
        ##########################################################
        ##########################################################
        ##########################################################

        mydb = mysql.connector.connect(
            host='localhost',
            user="root",
            passwd="2125253032",
            port="3306",
            database="patiens"
        )
        c = mydb.cursor()
        c.execute("SELECT * FROM add_win")
        # c.execute(f"""INSERT INTO add_win
        # VALUES ("asd","sfs","123","34","2000-11-11",'asfsdf')
        # """)
        a = c.fetchall()
        ########
        ########pip install mysql-connector-python
        ############
        mydb.commit()
        mydb.close()
##########################################################
        ##########################################################
        ##########################################################
        self.retranslateUi(show_win)
        QtCore.QMetaObject.connectSlotsByName(show_win)

    def retranslateUi(self, show_win):
        _translate = QtCore.QCoreApplication.translate
        show_win.setWindowTitle(_translate("show_win", "Records"))
        self.treeWidget.headerItem().setText(0, _translate("show_win", "id no "))
        self.treeWidget.headerItem().setText(1, _translate("show_win", "first name"))
        self.treeWidget.headerItem().setText(2, _translate("show_win", "last name"))
        self.treeWidget.headerItem().setText(3, _translate("show_win", "phone no"))
        self.treeWidget.headerItem().setText(4, _translate("show_win", "price"))
        self.treeWidget.headerItem().setText(5, _translate("show_win", "Depend"))
        self.treeWidget.headerItem().setText(6, _translate("show_win", "last payment"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("show_win", "1"))
        self.treeWidget.topLevelItem(0).setText(1, _translate("show_win", "None"))
        self.treeWidget.topLevelItem(0).setText(2, _translate("show_win", "henry"))
        self.treeWidget.topLevelItem(0).setText(3, _translate("show_win", "569445332"))
        self.treeWidget.topLevelItem(0).setText(4, _translate("show_win", "49 $"))
        self.treeWidget.topLevelItem(0).setText(5, _translate("show_win", "None"))
        self.treeWidget.topLevelItem(0).setText(6, _translate("show_win", "1/1/2020"))
        self.treeWidget.topLevelItem(0).child(0).setText(0, _translate("show_win", "2"))
        self.treeWidget.topLevelItem(0).child(0).setText(1, _translate("show_win", "gule"))
        self.treeWidget.topLevelItem(0).child(0).setText(2, _translate("show_win", "ajram"))
        self.treeWidget.topLevelItem(0).child(0).setText(3, _translate("show_win", "56456"))
        self.treeWidget.topLevelItem(0).child(0).setText(4, _translate("show_win", "43"))
        self.treeWidget.topLevelItem(0).child(0).setText(5, _translate("show_win", "1"))
        self.treeWidget.topLevelItem(0).child(0).setText(6, _translate("show_win", "1/1/2023"))
        self.treeWidget.topLevelItem(0).child(1).setText(0, _translate("show_win", "3"))
        self.treeWidget.topLevelItem(0).child(1).setText(1, _translate("show_win", "hevidar"))
        self.treeWidget.topLevelItem(0).child(1).setText(2, _translate("show_win", "yenge"))
        self.treeWidget.topLevelItem(0).child(1).setText(3, _translate("show_win", "4534534"))
        self.treeWidget.topLevelItem(0).child(1).setText(4, _translate("show_win", "56"))
        self.treeWidget.topLevelItem(0).child(1).setText(5, _translate("show_win", "1"))
        self.treeWidget.topLevelItem(0).child(1).setText(6, _translate("show_win", "1/2/2022"))
        self.treeWidget.topLevelItem(1).setText(0, _translate("show_win", "2"))
        self.treeWidget.topLevelItem(1).setText(1, _translate("show_win", "Gjule"))
        self.treeWidget.topLevelItem(1).setText(2, _translate("show_win", "Ajram"))
        self.treeWidget.topLevelItem(1).setText(3, _translate("show_win", "507301 1223"))
        self.treeWidget.topLevelItem(1).setText(4, _translate("show_win", "32 $"))
        self.treeWidget.topLevelItem(1).setText(5, _translate("show_win", "1"))
        self.treeWidget.topLevelItem(1).setText(6, _translate("show_win", "1/1/2023"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.lineEdit.setText(_translate("show_win", "first input"))
        self.pushButton.setText(_translate("show_win", "Serach"))
        self.pushButton_2.setText(_translate("show_win", "Change It"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    show_win = QtWidgets.QMainWindow()
    ui = Ui_show_win()
    ui.setupUi(show_win)
    show_win.show()
    sys.exit(app.exec_())
